name: GitHub 3D Profile

on:
  schedule:
    # Runs at 12am UTC (5:30am IST)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D profile contribution
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      
      # Run the generation action
      - name: Generate 3D profile contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: ${{ github.repository_owner }}
          
      # Commit and push if there are changes
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main --rebase
          git add -A .
          git commit -m "Generated 3D profile contribution" || exit 0
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
