name: GitHub 3D Profile

on:
  schedule:
    # Runs at 12am UTC (5:30am IST)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D profile contribution
    steps:
      # Checkout repository with PAT for authentication
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      # Set up Git identity
      - name: Set Git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      # Run the generation action
      - name: Generate 3D profile contribution
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: ${{ github.repository_owner }}
      
      # Commit and push
      - name: Commit & Push
        run: |
          # Check if there are changes
          if git status --porcelain | grep .; then
            # Pull latest changes with rebase
            git pull origin main --rebase
            
            # Add all changes
            git add -A .
            
            # Commit changes
            git commit -m "Updated 3D profile contribution"
            
            # Push changes
            git push origin main
            
            echo "Successfully pushed new 3D profile contributions"
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
